### ISSUE TITLE
[!] This release was not published with your preferred format.

### ISSUE THREAD

**Issue by bendwyer** [cobalamin/drip-downloader#4]
Hi! I'm receiving the error below when trying to download from OWSLA's drip. Is it because of the `$` in the release title?

`It G Ma Remix (feat. A$AP Ferg, Father, Waka Flocka Flame, Dumbfoundead)` https://drip.com/owsla/releases/5016

The release in question actually is available to download in my preferred format (FLAC).

```
We've got "It G Ma Remix (feat. A$AP Ferg, Father, Waka Flocka Flame, Dumbfoundead)" by Keith Ape.
[!] This release was not published with your preferred format.
/home/ben/drip/drip.rb:43:in `choose': undefined method `join' for {"errors"=>["Release not found"]}:Hash (NoMethodError)
        from /home/ben/drip/drip.rb:244:in `fetch_release'
        from /home/ben/drip/drip.rb:231:in `block in grab_releases'
        from /home/ben/drip/drip.rb:204:in `each'
        from /home/ben/drip/drip.rb:204:in `grab_releases'
        from /home/ben/drip/drip.rb:137:in `initialize'
        from /home/ben/drip/drip.rb:350:in `new'
        from /home/ben/drip/drip.rb:350:in `<main>'
```

**Comment by cobalamin** [comment]
I see what the problem is. For some reason, drip does not generate a release slug (maybe because of the $ in the name as you noted). So I updated the script to use the id instead. I can't really test it with this release since I don't have it myself, but let me know if it works with the newest commit.

**Comment by bendwyer** [comment]
It works! Thanks.
