### ISSUE TITLE
Crash upon entering password

### ISSUE THREAD

**Issue by IkarosAV** [cobalamin/drip-downloader#7]
After entering email and password, a couple of seconds delay is followed by a crash of ruby.exe. The error reads just C:/Ryby23-x64/lib/ruby/2.3.0/net/http.rb:933:in 'connect_nonblock'
I'm using ruby 2.3.3, latest httparty and rubyzip. Also tried installing the version numbers from the gemfile, and uninstalling the old ones, same deal.

Then I noticed the ruby 2.0.0 version number in the gemfile, went back to that, couldn't install httparty there cause it required json 1.8, which it refused to install since it's 'native' (and it also required update of multi_xml to 0.5.2).

Then I went up to ruby 2.1.0, where i just had to update multi_xml to install httparty, then rubyzip, and we're off with a new error, a longer one, more stack on the bone.
Password: C:/Ruby21-x64/lib/ruby/2.1.0/net/http.rb:923:in 'connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError) 
from C:/Ruby21-x64/11b/ruby/2.1.0/net/http.rb:923:in 'block in connect' 
from C:/Ruby21-x64/11b/ruby/2.1.0/timeout.rb:75:in 'timeout' 
from C:/Ruby21-x64/lib/ruby/2.1.0/net/http.rb:923:in 'connect' 
from C:/Ruby21-x64/lib/ruby/2.1.0/net/http.rb:863:in 'do_start. 
from C:/Ruby21-x64/11b/ruby/2.1.0/net/http.rb:852:in 'start' 
from C:/Ruby21-x64/11b/ruby/2.1.0/net/http.rb:1375:in 'request' 
from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/httparty-0.13.1/lib/httpart/request.rb:93:in 'perform' 
from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/httparty-0.13.1/lib/httpart.rb:521:in 'perform_request. 
from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/httparty-0.13.1/lib/httpart.rb:473:in 'post' 
from C:/Users/Ikaro/Desktop/dripdownloader2/drip.rb:62:in 'send_login_request' 
from C:/Users/Ikaro/Desktop/dripdownloader2/drip.rb:121:in 'initialize' 
from C:/Users/Ikaro/Desktop/dripdownloader2/drip.rb:354:in 'new' 
from C:/Users/Ikaro/Desktop/dripdownloader2/drip.rb:354:in '<main>' 

Finally, I got stubborn and installed 2.0.0 again and it's devkit so json could get installed, installed json, multi_xml, then httparty and rubyzip, and got roughly the same error stack as 2.1.0, but here's a copy.
Password: C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:921:in 'connect': SSL_connect returned=l errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError) 
from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:921:in 'block in connect' 

from C:/Ruby200-x64/lib/ruby/2.0.0/timeout.rb:52:in 'timeout' 
from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:921:in 'connect' 
from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:862:in 'do_start'
from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:851:in 'start' 
from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:1373:in 'request' 
from C:/Ruby200-x64/11b/ruby/gems/2.0.0/gems/httparty-0.13.1/11b/httparty/request.rb:93:in 'perform' 
from C:/Ruby200-x64/11b/ruby/gems/2.0.0/gems/httparty-0.13.1/11b/httparty.rb:521:in 'perform_request' 
from C:/Ruby200-x64/11b/ruby/gems/2.0.0/gems/httparty-0.13.1/11b/httparty.rb:473:in 'post' 
from C:/Users/Ikaro/Desktop/dripdownloader2/drip.rb:62:in 'send_login_request'
from C:/Users/Ikaro/Desktop/dripdownloader2/drip.rb:121:in 'initialize' 
from C:/Users/Ikaro/Desktop/dripdownloader2/drip.rb:354:in 'new' 
from C:/Users/Ikaro/Desktop/dripdownloader2/drip.rb:354:in '<main>' 

I might be doing something fundamentally wrong, this is the first time I'm executing/using ruby, normally I work with games. I attached some crash gifs if for some reason that helps.

I'm really hoping to get your tool, or the other one (downode) working, since owsla and mad decent have both pulled out it'd be nice to get those files out before closing the account or drip shuts down, thanks in advance!
![20](https://cloud.githubusercontent.com/assets/11332255/25598791/560d440a-2ed7-11e7-9db8-6050f892bee3.gif)
![21](https://cloud.githubusercontent.com/assets/11332255/25598792/560e7d20-2ed7-11e7-982f-cb0b509f9a26.gif)
![23](https://cloud.githubusercontent.com/assets/11332255/25598790/560b6bda-2ed7-11e7-8197-8a86dd501822.gif)

**Comment by cobalamin** [comment]
I've just tried the script a fresh install via RVM on Ubuntu and everything is working fine for me. After a little research, this seems to be an issue with your Ruby installation - namely, it's lacking a bundle of required certificates for properly connecting via SSL. I've found some info on how to possibly fix this:

http://stackoverflow.com/questions/4528101/ssl-connect-returned-1-errno-0-state-sslv3-read-server-certificate-b-certificat

**Comment by IkarosAV** [comment]
Alright, that did it! Manually downloaded the .pem and set it as an env var in the windows control panel. Thanks a billion for the quick help! Now it's fetching the first 237 releases, should be just overnight, this script is gold right now!

**Comment by cobalamin** [comment]
Cheers, glad that did the trick! Happy to hear it's helping you out :)
