### ISSUE TITLE
401 Unauthorized. Retrying.

### ISSUE THREAD

**Issue by bendwyer** [cobalamin/drip-downloader#9]
The tool is working great, but it is coming across some music that has either moved or been deleted on the Drip side.

```
[!] An error occurred while downloading Sin City: "401 Unauthorized". Retrying.
Saving to "Mad Decent Premium/yellow-claw-sin-city.zip", please stand by while this release is being fetched...
```

Once it reaches this point it simply keeps re-attempting the download and does not proceed. Is there a way to have it skip attempting the download after, say, 10 or so tries? At this point I'm just trying to grab what I can.

Here is the release in question: https://drip.kickstarter.com/mad-decent/releases/5790. It looks like it is generating the error because it is open for editing.

**Comment by cobalamin** [comment]
The last commit changes it so it skips releases that error. I think that's the most sensible way for grabbing as much as we can.

**Comment by bendwyer** [comment]
Thanks for the quick turnaround. Good news is it doesn't get stuck anymore. Bad news is it crashes out on that release instead.

```
We've got "Sin City" by Yellow Claw.
Saving to "Mad Decent Premium/yellow-claw-sin-city.zip", please stand by while this release is being fetched...
An error occurred downloading Sin City: 401 Unauthorized. Skipping.
/usr/src/app/drip.rb:242:in `copy_stream': undefined method `read' for nil:NilClass (NoMethodError)
        from /usr/src/app/drip.rb:242:in `fetch_release'
        from /usr/src/app/drip.rb:207:in `block in grab_releases'
        from /usr/src/app/drip.rb:186:in `each'
        from /usr/src/app/drip.rb:186:in `grab_releases'
        from /usr/src/app/drip.rb:141:in `initialize'
        from /usr/src/app/drip.rb:303:in `new'
        from /usr/src/app/drip.rb:303:in `<main>'
```

**Comment by cobalamin** [comment]
should be fixed.

**Comment by bendwyer** [comment]
That got me past the error. Thanks so much for the quick fixes!
